config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :customers
  resources :products
  resources :orders
  resources :ordrs
  resources :addresses
  #get 'home/index'
  get 'home/about'
  get 'home/product'
  get 'home/order'
  get 'home/ordr'
  get 'home/customer'
  get 'home/address'
  root 'home#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ordr.rb
class Ordr < ApplicationRecord
end

app/controllers/ordrs_controller.rb
class OrdrsController < ApplicationController
  before_action :set_ordr, only: %i[ show edit update destroy ]

  # GET /ordrs or /ordrs.json
  def index
    @ordrs = Ordr.all
  end

  # GET /ordrs/1 or /ordrs/1.json
  def show
  end

  # GET /ordrs/new
  def new
    @ordr = Ordr.new
  end

  # GET /ordrs/1/edit
  def edit
  end

  # POST /ordrs or /ordrs.json
  def create
    @ordr = Ordr.new(ordr_params)

    respond_to do |format|
      if @ordr.save
        format.html { redirect_to @ordr, notice: "Ordr was successfully created." }
        format.json { render :show, status: :created, location: @ordr }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ordr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordrs/1 or /ordrs/1.json
  def update
    respond_to do |format|
      if @ordr.update(ordr_params)
        format.html { redirect_to @ordr, notice: "Ordr was successfully updated." }
        format.json { render :show, status: :ok, location: @ordr }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ordr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordrs/1 or /ordrs/1.json
  def destroy
    @ordr.destroy
    respond_to do |format|
      format.html { redirect_to ordrs_url, notice: "Ordr was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordr
      @ordr = Ordr.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ordr_params
      params.require(:ordr).permit(:orderno, :dateoforder, :status, :billingaddress, :shippingaddress)
    end
end

app/helpers/ordrs_helper.rb
module OrdrsHelper
end

app/views/ordrs/_form.html.erb
<%= form_with(model: ordr) do |form| %>
  <% if ordr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordr.errors.count, "error") %> prohibited this ordr from being saved:</h2>

      <ul>
        <% ordr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :orderno %>
    <%= form.text_field :orderno %>
  </div>

  <div class="field">
    <%= form.label :dateoforder %>
    <%= form.text_field :dateoforder %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :billingaddress %>
    <%= form.text_field :billingaddress %>
  </div>

  <div class="field">
    <%= form.label :shippingaddress %>
    <%= form.text_field :shippingaddress %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordrs/edit.html.erb
<h1>Editing Ordr</h1>

<%= render 'form', ordr: @ordr %>

<%= link_to 'Show', @ordr %> |
<%= link_to 'Back', ordrs_path %>

app/views/ordrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordrs</h1>

<table>
  <thead>
    <tr>
      <th>Orderno</th>
      <th>Dateoforder</th>
      <th>Status</th>
      <th>Billingaddress</th>
      <th>Shippingaddress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordrs.each do |ordr| %>
      <tr>
        <td><%= ordr.orderno %></td>
        <td><%= ordr.dateoforder %></td>
        <td><%= ordr.status %></td>
        <td><%= ordr.billingaddress %></td>
        <td><%= ordr.shippingaddress %></td>
        <td><%= link_to 'Show', ordr %></td>
        <td><%= link_to 'Edit', edit_ordr_path(ordr) %></td>
        <td><%= link_to 'Destroy', ordr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordr', new_ordr_path %>

app/views/ordrs/new.html.erb
<h1>New Ordr</h1>

<%= render 'form', ordr: @ordr %>

<%= link_to 'Back', ordrs_path %>

app/views/ordrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orderno:</strong>
  <%= @ordr.orderno %>
</p>

<p>
  <strong>Dateoforder:</strong>
  <%= @ordr.dateoforder %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ordr.status %>
</p>

<p>
  <strong>Billingaddress:</strong>
  <%= @ordr.billingaddress %>
</p>

<p>
  <strong>Shippingaddress:</strong>
  <%= @ordr.shippingaddress %>
</p>

<%= link_to 'Edit', edit_ordr_path(@ordr) %> |
<%= link_to 'Back', ordrs_path %>